-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgb6+PxyBZwUeUU2mb
GUePOpWqhfp5z8/0KsVErndeH9GgCgYIKoZIzj0DAQehRANCAARExiHydRcUTV5A
JBbXZa7EUsTFQAFn4dAGhiOmRQj2riLudSuvc0igtUiF1HWZb37hFSJHE6tdTAoK
04Ejw65e
-----END PRIVATE KEY-----